### PR TITLE
Policy violations

### PR DESCRIPTION
**Pull request by HagarJNode**
I added policy violation to the plugin, so that it can react to the policies that may be configurated in/on the Dependency Track server. 

https://github.com/DependencyTrack/dependency-track/discussions/1774

New feature:
https://github.com/jenkinsci/dependency-track-plugin/issues/130

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by HagarJNode** [comment]
I don't know what that "Unable to load component class org.sonar.scanner.rule.QualityProfiles" is all about - I guess it's not from my hands.

**Comment by HagarJNode** [comment]
Btw. someone german should take a look on the german texts, as I'm dane and german.

**Comment by HagarJNode** [comment]
I see that the pull request from lsoumille (https://github.com/jenkinsci/dependency-track-plugin/pull/113) has the same issue.

**Comment by HagarJNode** [comment]
@sephiroth-j any chance you could take a look at my pull request?

**Comment by seittema** [comment]
Would love to see this get pulled into the plugin as we are right now needing the ability to fail on policy violations and this would prevent us from doing some workarounds.

**Comment by 37b** [comment]
Would love to see this

**Comment by taa-autorola-com** [comment]
This would be great - it would solve a headache for us

**Comment by dennisverheijen** [comment]
We also have need for the ability to fail the build on a policy violation, any updates?

**Comment by sephiroth-j** [comment]
superseded by #269

**Pull request closed without merging**
